DROP TABLE IF EXISTS BILIONARIOS;
DROP TABLE IF EXISTS BILIONARIOS_SEM_VALID;

CREATE TABLE BILIONARIOS (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  PRIMEIRO_NOME VARCHAR(250) NOT NULL,
  ULTIMO_NOME VARCHAR(250) NOT NULL,
  CARREIRA VARCHAR(250) DEFAULT NULL
);
 
INSERT INTO BILIONARIOS (PRIMEIRO_NOME, ULTIMO_NOME, CARREIRA) VALUES
  ('Aliko', 'Dangote', 'Billionaire Industrialist'),
  ('Bill', 'Gates', 'Billionaire Tech Entrepreneur'),
  ('Folrunsho', 'Alakija', 'Billionaire Oil Magnate');

CREATE TABLE BILIONARIOS_SEM_VALID (
    BILIONARIO_ID int NOT NULL,
    CONSTRAINT FK_BILIONARIOS_VALID FOREIGN KEY (BILIONARIO_ID)
    REFERENCES BILIONARIOS(ID)
);

INSERT INTO BILIONARIOS_SEM_VALID (BILIONARIO_ID) VALUES(1)


